[package]
name = "rajsite/exorbitant"
version = "0.0.20"
description = "Web calculator library"
license = "MIT"
repository = "git+https://github.com/rajsite/exorbitant.git"
readme = "README.md"
homepage = "https://github.com/rajsite/exorbitant"

[[module]]
name = "exorbitant"
source = "dist/exprtkcore.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "exorbitant"
module = "exorbitant"
package = "rajsite/exorbitant"
