name: exorbitant ci

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run install:wasi-sdk:win
    - run: choco install make -y
    - run: choco install gnuwin32-coreutils.portable -y
    - run: make
    - run: npm pack
    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: exorbitant archive
        path: ./exorbitant-*.tgz
    - run: npm test
    - run: npm run lint
