name: exorbitant ci

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install gnu tools
      run: |
        chocolatey install make -y
        chocolatey install gnuwin32-coreutils.portable -y
    - name: Install emscripten
      run: |
        imports\emsdk\emsdk install sdk-1.39.4-64bit
        imports\emsdk\emsdk activate sdk-1.39.4-64bit
    - name: Build exorbitant
      run: |
        imports\emsdk\emsdk_env.ps1
        emmake make build
    - name: Upload binaries
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ./dist
