name: exorbitant ci

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '15'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: chocolatey install make -y
    - run: chocolatey install gnuwin32-coreutils.portable -y
    - run: npm run install:emsdk
    - name: Build
      run: |
        imports\emsdk\emsdk_env.ps1
        npm run build
    - run: npm pack
    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: exorbitant archive
        path: ./exorbitant-*.tgz
    - run: npm test
