name: exorbitant ci

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install dependencies
      run: |
        npm ci
    - name: Install gnu tools
      run: |
        chocolatey install make -y
        chocolatey install gnuwin32-coreutils.portable -y
    - name: Install emscripten
      run: |
        imports\emsdk\emsdk install 3.0.1
        imports\emsdk\emsdk activate 3.0.1
    - name: Build exorbitant
      run: |
        imports\emsdk\emsdk_env.ps1
        emmake make build
        npm pack
    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: exorbitant archive
        path: ./exorbitant-*.tgz
